require("raulvargas.plugins-setup")
require("raulvargas.core.options")
require("raulvargas.core.keymaps")
require("raulvargas.core.colorscheme")
require("raulvargas.plugins.comment")
require("raulvargas.plugins.lualine")
require("raulvargas.plugins.nvim-tree")
require("raulvargas.plugins.telescope")
require("raulvargas.plugins.mvim-cmp")
require("raulvargas.plugins.autopairs")
require("raulvargas.plugins.treesitter")
require("raulvargas.plugins.vgit")
require("raulvargas.plugins.bufferline")
-- lsp
require("raulvargas.plugins.lsp.mason")
require("raulvargas.plugins.lsp.lspconfig")
require("raulvargas.plugins.lsp.lspsaga")
require("raulvargas.plugins.lsp.null-ls")
